spring.application.name=reservetech

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.web.pageable.serialization-mode=via-dto

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.nome=${ADMIN_NAME:Administrador}

backup.secret=${BACKUP_SECRET}

email.api-key=${EMAIL_API_KEY}
email.remetente=${EMAIL_REMETENTE}
app.url=${APP_URL:https://reservetech-frontend-teal.vercel.app}